### ISSUE TITLE
update target env to Wildfly 10 final

### ISSUE THREAD

**Issue by yntelectual** [yntelectual/nlighten#21]
Since WF 10 final is out, we should update the maven & arquillian to the new version.

**Comment by Mersenne255** [comment]
The project was Wildfly 10 ready right from the beginning.
Version used in pom is 10.0.0.CR4 and Arquilian tests are running as well.
Is there something else we need to have a look at?

**Comment by yntelectual** [comment]
CR4 is Candidate Release 4 - e.g. not stable yet. Few weeks ago, Wildfly released 10.0.0.Final therefore we should update all dependencies to the final version.

**Comment by Mersenne255** [comment]
Backend project dependencies changed for Wildfly 10.0.0.Final

**Comment by yntelectual** [comment]
closed in [533759b](https://github.com/yntelectual/nlighten/commit/533759b661d8110a29638b5bcb8f74be52b56298)
