### ISSUE TITLE
DAOException hides cause

### ISSUE THREAD

**Issue by yntelectual** [yntelectual/nlighten#34]
DAOException hides the cause by ignoring it in its constructor:
```java
 public DAOException(Enum<?> messageKey, Object... arguments) {
    this.messageKey = messageKey;
    this.arguments = arguments;
  }
```
Either check the array args for the presence of exception, or add `cause` as required constructor param.

Also remove all constructors, that take `String` as argument. It is pointless to allow raw strings as parameters, as there is no way to i18n them. Only allow enums, Exceptions, and params.

**Comment by lubo3** [comment]
Issue was fixed with "fix for DAOException hides cause bug" branch.
