### ISSUE TITLE
setup i18n support

### ISSUE THREAD

**Issue by yntelectual** [yntelectual/nlighten#6]
# i18n utility

* implement an i18n utility, that is able to match Enum values to java properties files and provide translations based on Locale.   
Example `String message = I18nUtil.translate(MyCoolEnum.ERROR_DUMB,"EN")`
* implement resource bundle loading based on the FQN name of the enum key and locale
* add support for optional parameters - client can supply an optional array or params that should be interpolated to the message
* define a format, in which the keys of resource bundle have to be created .e.g. CamelCase, CONSTANT_CASE,... and how would it match the Enum Keys.  
* suggest naming convention for Resource enums, packages..
* create a simple Junit test case for this functionality - in `src/main/test` prepare a test enum, test properties and test the results.

**Comment by Mersenne255** [comment]
Please review latest push.
Formatting convention is as follows:
For a translation to be successful, there needs to be a match between Enum class with name [className] and property file in the resource folder under the path 'translations/[className]/[className]_[locale].properties'.
Keys must be defined exactly like their respective enum values (which should be defined in CamelCase, according to Java general conventions).
Any other suggestions are welcome.

**Comment by yntelectual** [comment]
I generally like the implementation, however I do have some remarks:

- add some(brief) information about i18n to the docs either in `nlighten-backend/docs/README.md`or in a dedicated file.md
- in `I18nUtil#translate` store the fallback locale in a static var. Right now you unnecessarily create a new `Locale` object every time a `translate` method is invoked without locale.
- in `I18nUtil#translate` - Use `MessageFormat#format` static method instead of creating a new instance everytime. 
- missing error handling - e.g. no resouce bundle can be loaded. 
- Enum naming conventions: Enum as a class is a type and should be named in camelCase e.g. `MyErrorMessageKeys`, however enum values are constants and should be named in CONSTANT_CASE. See [java official example for more info](http://docs.oracle.com/javase/tutorial/java/javaOO/enum.html)
- Enum-prop file matching: although the suggested approach is simpler and less verbose, I would prefer the more robust approach with [FQN](https://en.wikipedia.org/wiki/Fully_qualified_name) mathing, i.e. bundles need to be accessible in runtime under the same package as the Enum with the keys. The main reason for this, is that as the projects grow, it is almost inevitable that some Enums will have the same name e.g. `ErrorKeys`. matching based on simple name would not suffice in this case to distinguish the different enums. Also image a project where you bundle a bunch of libs together. Each of them might have an Enum with the same name and once they are in the same classpath, the I18n would go haywire. 

Testcases look great, I would only suggest to add some negative testcases - e.g. No bundle defined for given language(fallback to default locale), or no bundles defined at all...

btw: prefer  pull requests to discuss implementation details in the future, as it is not possible to compare changes between branches here
